# Archivo: secrets.toml

GOOGLE_API_KEY = "AIzaSyD0o-zuTp7VZFKiBQs3qKuionxMQPmdKZo"
GEMINI_API_KEY = "AIzaSyCG-wlXv21tQUwi87_oS_pDZmxMWN3cAyQ"

# Configuraci√≥n de Correo (Tu App Password de 16 letras)
EMAIL_SENDER = "Mnsamame@gmail.com"
EMAIL_PASSWORD = "wzkh kdsq hzkw aknq"